function renderTopBar() {
  return '<div class="top-bar"><div class="container top-bar-inner"><div class="top-bar-left"><span><i class="fas fa-phone-alt"></i> <a href="tel:+919662526472">+91 96625 26472</a></span><span><i class="fas fa-map-marker-alt"></i> <a href="contact-us.html">Gujarat, India</a></span></div><div class="top-bar-right"><span><i class="far fa-clock"></i> Mon - Sun: 8:30 am - 6:30 pm</span></div></div></div>';
}
function renderHeader(activePage) {
  var a = function(p) { return p === activePage ? 'class="active"' : ''; };
  return '<header id="site-header"><div class="container header-inner"><div class="logo"><a href="../index.html"><img src="../images/logo.svg" alt="Omex Medical Technology"></a></div><nav class="main-nav"><ul><li><a href="../index.html" ' + a('home') + '>Home</a></li><li><a href="../about-us.html" ' + a('about') + '>About Us</a></li><li class="has-dropdown"><a href="#">Product <i class="fas fa-chevron-down"></i></a><ul class="dropdown"><li><a href="../product-category/urology.html">Urology</a></li><li><a href="../product-category/infusion-transfusion.html">Infusion & Transfusion</a></li><li><a href="../product-category/gastroenterology.html">Gastroenterology</a></li><li><a href="../product-category/anesthesia-care.html">Anesthesia Care</a></li><li><a href="../product-category/surgery-wound-care.html">Surgery & Wound Care</a></li><li><a href="../product-category/miscellaneous-range.html">Miscellaneous Range</a></li><li><a href="../product-category/orthopedic-range.html">Orthopedic Range</a></li><li><a href="../product-category/body-belt-braces.html">Body Belt & Braces</a></li></ul></li><li><a href="../certificate.html" ' + a('certificate') + '>Certificate</a></li><li><a href="../download.html" ' + a('download') + '>Download</a></li><li><a href="../blog.html" ' + a('blog') + '>Blog</a></li><li><a href="../contact-us.html" ' + a('contact') + '>Contact Us</a></li></ul></nav><div class="header-actions"><a href="tel:+919662526472" class="header-phone"><i class="fas fa-phone-alt"></i> +91 96625 26472</a></div><button class="hamburger" id="hamburger"><span></span><span></span><span></span></button></div></header>';
}
function renderHeaderRoot(activePage) {
  var a = function(p) { return p === activePage ? 'class="active"' : ''; };
  return '<header id="site-header"><div class="container header-inner"><div class="logo"><a href="index.html"><img src="images/logo.svg" alt="Omex Medical Technology"></a></div><nav class="main-nav"><ul><li><a href="index.html" ' + a('home') + '>Home</a></li><li><a href="about-us.html" ' + a('about') + '>About Us</a></li><li class="has-dropdown"><a href="#">Product <i class="fas fa-chevron-down"></i></a><ul class="dropdown"><li><a href="product-category/urology.html">Urology</a></li><li><a href="product-category/infusion-transfusion.html">Infusion & Transfusion</a></li><li><a href="product-category/gastroenterology.html">Gastroenterology</a></li><li><a href="product-category/anesthesia-care.html">Anesthesia Care</a></li><li><a href="product-category/surgery-wound-care.html">Surgery & Wound Care</a></li><li><a href="product-category/miscellaneous-range.html">Miscellaneous Range</a></li><li><a href="product-category/orthopedic-range.html">Orthopedic Range</a></li><li><a href="product-category/body-belt-braces.html">Body Belt & Braces</a></li></ul></li><li><a href="certificate.html" ' + a('certificate') + '>Certificate</a></li><li><a href="download.html" ' + a('download') + '>Download</a></li><li><a href="blog.html" ' + a('blog') + '>Blog</a></li><li><a href="contact-us.html" ' + a('contact') + '>Contact Us</a></li></ul></nav><div class="header-actions"><a href="tel:+919662526472" class="header-phone"><i class="fas fa-phone-alt"></i> +91 96625 26472</a></div><button class="hamburger" id="hamburger"><span></span><span></span><span></span></button></div></header>';
}
function renderFooter() {
  return '<footer class="site-footer"><div class="container"><div class="footer-grid"><div class="footer-col footer-about"><img src="../images/logo.svg" alt="Omex Medical Technology" class="footer-logo"><p>The company provides a wide range of facilities to its customers. We provide medical devices for Infusion Therapy, Transfusion Therapy, Gastroenterology, urology, Anesthesia, surgery, and other disposable products.</p></div><div class="footer-col"><h4>Quick Products</h4><ul><li><a href="#">Gynec Range</a></li><li><a href="#">Surgery Range</a></li><li><a href="#">Hand Gloves</a></li><li><a href="#">Nephrology Range</a></li><li><a href="#">Blood collection tubes</a></li><li><a href="#">Intravenous Infusion Therapy Range</a></li></ul></div><div class="footer-col"><h4>Quick Products</h4><ul><li><a href="../product-category/urology.html">Urology</a></li><li><a href="../product-category/infusion-transfusion.html">Infusion & Transfusion</a></li><li><a href="../product-category/gastroenterology.html">Gastroenterology</a></li><li><a href="../product-category/anesthesia-care.html">Anesthesia Care</a></li><li><a href="../product-category/surgery-wound-care.html">Surgery & Wound Care</a></li><li><a href="../product-category/miscellaneous-range.html">Miscellaneous Range</a></li><li><a href="../product-category/orthopedic-range.html">Orthopedic Range</a></li><li><a href="../product-category/body-belt-braces.html">Body Belt & Braces</a></li></ul></div><div class="footer-col footer-contact"><h4>Quick Contacts</h4><p>If you have any questions or need help, feel free to contact us for any type of assistance.</p><ul class="contact-list"><li><i class="fas fa-phone-alt"></i> <a href="tel:+919662526472">+91 96625 26472</a></li><li><i class="fas fa-phone-alt"></i> <a href="tel:+919426313688">+91 94263 13688</a></li><li><i class="fas fa-envelope"></i> <a href="mailto:infoomex@gmail.com">infoomex@gmail.com</a></li></ul><p class="footer-address"><i class="fas fa-map-marker-alt"></i> Plot No:1, Shivalik Industrial Park,<br>At: Kotadi, Vijapur, Gujarat 382850, India</p><a href="https://goo.gl/maps/gU3WRj6TbkU3Aqi88" class="btn btn-sm" target="_blank">Get Direction</a><div class="social-links"><a href="https://www.facebook.com/omexmedicaltechnology/" target="_blank"><i class="fab fa-facebook-f"></i></a><a href="https://in.linkedin.com/company/omex-medical-technology" target="_blank"><i class="fab fa-linkedin-in"></i></a></div></div></div></div><div class="footer-bottom"><div class="container"><p>&copy; 2025 Omex Medical Technology. All rights reserved. Design & Development By Techosoft</p></div></div></footer>';
}
function renderFooterRoot() {
  return '<footer class="site-footer"><div class="container"><div class="footer-grid"><div class="footer-col footer-about"><img src="images/logo.svg" alt="Omex Medical Technology" class="footer-logo"><p>The company provides a wide range of facilities to its customers. We provide medical devices for Infusion Therapy, Transfusion Therapy, Gastroenterology, urology, Anesthesia, surgery, and other disposable products.</p></div><div class="footer-col"><h4>Quick Products</h4><ul><li><a href="#">Gynec Range</a></li><li><a href="#">Surgery Range</a></li><li><a href="#">Hand Gloves</a></li><li><a href="#">Nephrology Range</a></li><li><a href="#">Blood collection tubes</a></li><li><a href="#">Intravenous Infusion Therapy Range</a></li></ul></div><div class="footer-col"><h4>Quick Products</h4><ul><li><a href="product-category/urology.html">Urology</a></li><li><a href="product-category/infusion-transfusion.html">Infusion & Transfusion</a></li><li><a href="product-category/gastroenterology.html">Gastroenterology</a></li><li><a href="product-category/anesthesia-care.html">Anesthesia Care</a></li><li><a href="product-category/surgery-wound-care.html">Surgery & Wound Care</a></li><li><a href="product-category/miscellaneous-range.html">Miscellaneous Range</a></li><li><a href="product-category/orthopedic-range.html">Orthopedic Range</a></li><li><a href="product-category/body-belt-braces.html">Body Belt & Braces</a></li></ul></div><div class="footer-col footer-contact"><h4>Quick Contacts</h4><p>If you have any questions or need help, feel free to contact us for any type of assistance.</p><ul class="contact-list"><li><i class="fas fa-phone-alt"></i> <a href="tel:+919662526472">+91 96625 26472</a></li><li><i class="fas fa-phone-alt"></i> <a href="tel:+919426313688">+91 94263 13688</a></li><li><i class="fas fa-envelope"></i> <a href="mailto:infoomex@gmail.com">infoomex@gmail.com</a></li></ul><p class="footer-address"><i class="fas fa-map-marker-alt"></i> Plot No:1, Shivalik Industrial Park,<br>At: Kotadi, Vijapur, Gujarat 382850, India</p><a href="https://goo.gl/maps/gU3WRj6TbkU3Aqi88" class="btn btn-sm" target="_blank">Get Direction</a><div class="social-links"><a href="https://www.facebook.com/omexmedicaltechnology/" target="_blank"><i class="fab fa-facebook-f"></i></a><a href="https://in.linkedin.com/company/omex-medical-technology" target="_blank"><i class="fab fa-linkedin-in"></i></a></div></div></div></div><div class="footer-bottom"><div class="container"><p>&copy; 2025 Omex Medical Technology. All rights reserved. Design & Development By Techosoft</p></div></div></footer>';
}
function renderWhatsApp() {
  return '<a href="https://wa.me/919662526472" class="whatsapp-float" target="_blank"><i class="fab fa-whatsapp"></i></a>';
}
function renderEnquirePopup() {
  return '<div class="popup-overlay" id="enquirePopup"><div class="popup-content"><button class="popup-close">&times;</button><h3>Enquire Now</h3><p>Please feel welcome to contact our friendly reception staff with any general or Products enquiry.</p><form class="enquire-form"><div class="form-group"><select><option>Urology</option><option>Infusion & Transfusion</option><option>Gastroenterology</option><option>Anesthesia & Respiratory Care</option><option>Surgery & Wound Care</option><option>Miscellaneous Range</option><option>Orthopedic Range</option><option>Body Belt & Braces</option><option>Gynec Range</option><option>Surgery Range</option><option>Hand Gloves</option><option>Nephrology Range</option><option>Blood collection tubes</option><option>Intravenous Infusion Therapy Range</option></select></div><div class="form-group"><input type="text" placeholder="7 + 3 = ?" class="captcha-input"></div><button type="submit" class="btn btn-primary">Let\'s Go</button></form></div></div>';
}
